/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.tests;

import com.google.inject.Inject;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.example.mydsl.myDsl.Model;

@ExtendWith(InjectionExtension.class)
@InjectWith(MyDslInjectorProvider.class)
public class ParsingTest {
	@Inject
	ParseHelper<Model> parseHelper;
	
	@Test
	public void loadModel() throws Exception {
		var result = parseHelper.parse("Hello Xtext!");
		Assertions.assertNotNull(result);
		var errors = result.eResource().getErrors();
		assertEquals(true, errors.isEmpty(), "Unexpected errors");
	}
}
